name = "Snowflake"
uuid = "7bd9edc1-4fdc-40a1-a0f6-da58fb4f45eb"
authors = ["Alireza Yazdi <alireza@anyonsys.com>", "Paul Le Roux <pleroux@anyonsys.com>", "Facundo Sosa-Rey <facundo@anyonsys.com>", "Nicolas Poirier <nicolas.poirier2@mail.mcgill.ca>"]
version = "0.1.1-alpha"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
LinearAlgebra = "1.6.1"
StatsBase = "0.32 - 0.33"
julia = "1.6"
